### ISSUE TITLE
PNG geht nicht

### ISSUE THREAD

**Issue by sar-sturm** [weichware10/dokumente#11]
Die PNG-Generierung wirft eine Fehlermeldung, in VS Code geht das Ganze allerdings

https://github.com/weichware10/dokumente/blob/zoommaps_update/uml-class/zoommaps/kommentiert/zoommaps-notes.png

**Comment by joshuajeschek** [comment]
dürfte mit der neuen Action gehen, die ich soeben hochlade...
Vorgehensweise:
- aktuelles main bei dir reinmergen
- strich art ändern, neu pushen
- schauen obs geklappt hat

wenn es nicht geklappt hat, kannst du das issue wieder öffnen
